// Generated by pgen from sql/queries.sql against hooks. Do not edit: change the SQL and run pgen again.
//
// Each query is a function that runs it (`<name>`: the whole reply and a status, 0 for ok), one that only
// encodes the request for `pg.pool.submit` (`<name>_start`), and one accessor per result column
// (`<name>_<column>`, read from a row as `pg.first_row`/`pg.next_row` give it; `_is_null` where the
// column can be NULL). Call `prepare_all` once after login, before the first query (or give `prepare_script` to `pg.pool.reconnect`).
edition 5;

module queries;

import std.buffer;
import pg;

// add_attempt_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn add_attempt_start[&h](heap: &!h Heap, endpoint: int, event: int, replay: int, attempt: int, outcome: int, status: int, at_ms: int, latency_ms: int, reason: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, endpoint);
    ps = pg.param_int(heap, ps, event);
    ps = pg.param_int(heap, ps, replay);
    ps = pg.param_int(heap, ps, attempt);
    ps = pg.param_int(heap, ps, outcome);
    ps = pg.param_int(heap, ps, status);
    ps = pg.param_int(heap, ps, at_ms);
    ps = pg.param_int(heap, ps, latency_ms);
    ps = pg.param_int(heap, ps, reason);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "add_attempt", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// add_attempt: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn add_attempt[&h, &c](heap: &!h Heap, conn: &!c Conn, endpoint: int, event: int, replay: int, attempt: int, outcome: int, status: int, at_ms: int, latency_ms: int, reason: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, endpoint);
    ps = pg.param_int(heap, ps, event);
    ps = pg.param_int(heap, ps, replay);
    ps = pg.param_int(heap, ps, attempt);
    ps = pg.param_int(heap, ps, outcome);
    ps = pg.param_int(heap, ps, status);
    ps = pg.param_int(heap, ps, at_ms);
    ps = pg.param_int(heap, ps, latency_ms);
    ps = pg.param_int(heap, ps, reason);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "add_attempt", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

// prune_attempts_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn prune_attempts_start[&h](heap: &!h Heap, before: int, most: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, before);
    ps = pg.param_int(heap, ps, most);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "prune_attempts", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// prune_attempts: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn prune_attempts[&h, &c](heap: &!h Heap, conn: &!c Conn, before: int, most: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, before);
    ps = pg.param_int(heap, ps, most);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "prune_attempts", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

// attempts_of_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn attempts_of_start[&h](heap: &!h Heap, event: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, event);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "attempts_of", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// attempts_of: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn attempts_of[&h, &c](heap: &!h Heap, conn: &!c Conn, event: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, event);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "attempts_of", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn attempts_of_endpoint[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_replay[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 1);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_attempt[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 2);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_outcome[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 3);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_status[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 4);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_at_ms[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 5);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_latency_ms[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 6);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_reason[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 7);
    return pg.int_text(m, from, to);
}

// endpoints_all_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn endpoints_all_start[&h](heap: &!h Heap) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "endpoints_all", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// endpoints_all: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn endpoints_all[&h, &c](heap: &!h Heap, conn: &!c Conn) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "endpoints_all", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn endpoints_all_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn endpoints_all_host[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn endpoints_all_port[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 2);
    return pg.int_text(m, from, to);
}

pub fn endpoints_all_secret[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 3);
}

pub fn endpoints_all_types[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 4);
}

pub fn endpoints_all_headers[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 5);
}

pub fn endpoints_all_secret_old[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 6);
}

pub fn endpoints_all_secret_old_until[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 7);
    return pg.int_text(m, from, to);
}

pub fn endpoints_all_concurrency[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 8);
    return pg.int_text(m, from, to);
}

pub fn endpoints_all_rate[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 9);
    return pg.int_text(m, from, to);
}

// add_endpoint_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn add_endpoint_start[&h, &a2, &a4, &a5, &a6, &a7](heap: &!h Heap, id: int, host: &a2 [byte], port: int, secret: &a4 [byte], types: &a5 [byte], headers: &a6 [byte], secret_old: &a7 [byte], secret_old_until: int, concurrency: int, rate: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    ps = pg.param(heap, ps, types);
    ps = pg.param(heap, ps, headers);
    ps = pg.param(heap, ps, secret_old);
    ps = pg.param_int(heap, ps, secret_old_until);
    ps = pg.param_int(heap, ps, concurrency);
    ps = pg.param_int(heap, ps, rate);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "add_endpoint", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// add_endpoint: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn add_endpoint[&h, &c, &a2, &a4, &a5, &a6, &a7](heap: &!h Heap, conn: &!c Conn, id: int, host: &a2 [byte], port: int, secret: &a4 [byte], types: &a5 [byte], headers: &a6 [byte], secret_old: &a7 [byte], secret_old_until: int, concurrency: int, rate: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    ps = pg.param(heap, ps, types);
    ps = pg.param(heap, ps, headers);
    ps = pg.param(heap, ps, secret_old);
    ps = pg.param_int(heap, ps, secret_old_until);
    ps = pg.param_int(heap, ps, concurrency);
    ps = pg.param_int(heap, ps, rate);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "add_endpoint", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

// create_endpoint_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn create_endpoint_start[&h, &a1, &a3, &a4, &a5](heap: &!h Heap, host: &a1 [byte], port: int, secret: &a3 [byte], types: &a4 [byte], headers: &a5 [byte], concurrency: int, rate: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    ps = pg.param(heap, ps, types);
    ps = pg.param(heap, ps, headers);
    ps = pg.param_int(heap, ps, concurrency);
    ps = pg.param_int(heap, ps, rate);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "create_endpoint", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// create_endpoint: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn create_endpoint[&h, &c, &a1, &a3, &a4, &a5](heap: &!h Heap, conn: &!c Conn, host: &a1 [byte], port: int, secret: &a3 [byte], types: &a4 [byte], headers: &a5 [byte], concurrency: int, rate: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    ps = pg.param(heap, ps, types);
    ps = pg.param(heap, ps, headers);
    ps = pg.param_int(heap, ps, concurrency);
    ps = pg.param_int(heap, ps, rate);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "create_endpoint", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn create_endpoint_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

// patch_endpoint_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below. `keep_ms` is how long the previous secret is kept,
// counted by the **database's clock when the statement runs** (the row's `secret_old_until` is that moment plus `keep_ms`), not from when the request was sent: a change
// that waited for the database must not lose its overlap waiting, in the row any more than in memory (design 35.4); 0 ends the overlap.
pub fn patch_endpoint_start[&h, &a2, &a4, &a5, &a6](heap: &!h Heap, id: int, host: &a2 [byte], port: int, secret: &a4 [byte], secret_given: bool, types: &a5 [byte], types_given: bool, headers: &a6 [byte], headers_given: bool, keep_ms: int, keep_ms_given: bool, concurrency: int, concurrency_given: bool, rate: int, rate_given: bool) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    if secret_given {
        ps = pg.param(heap, ps, secret);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if types_given {
        ps = pg.param(heap, ps, types);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if headers_given {
        ps = pg.param(heap, ps, headers);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if keep_ms_given {
        ps = pg.param_int(heap, ps, keep_ms);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if concurrency_given {
        ps = pg.param_int(heap, ps, concurrency);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if rate_given {
        ps = pg.param_int(heap, ps, rate);
    } else {
        ps = pg.param_null(heap, ps);
    }
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "patch_endpoint", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// patch_endpoint: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn patch_endpoint[&h, &c, &a2, &a4, &a5, &a6](heap: &!h Heap, conn: &!c Conn, id: int, host: &a2 [byte], port: int, secret: &a4 [byte], secret_given: bool, types: &a5 [byte], types_given: bool, headers: &a6 [byte], headers_given: bool, keep_ms: int, keep_ms_given: bool, concurrency: int, concurrency_given: bool, rate: int, rate_given: bool) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    if secret_given {
        ps = pg.param(heap, ps, secret);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if types_given {
        ps = pg.param(heap, ps, types);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if headers_given {
        ps = pg.param(heap, ps, headers);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if keep_ms_given {
        ps = pg.param_int(heap, ps, keep_ms);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if concurrency_given {
        ps = pg.param_int(heap, ps, concurrency);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if rate_given {
        ps = pg.param_int(heap, ps, rate);
    } else {
        ps = pg.param_null(heap, ps);
    }
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "patch_endpoint", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn patch_endpoint_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

// patch_address_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn patch_address_start[&h, &a2](heap: &!h Heap, id: int, host: &a2 [byte], port: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "patch_address", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// patch_address: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn patch_address[&h, &c, &a2](heap: &!h Heap, conn: &!c Conn, id: int, host: &a2 [byte], port: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "patch_address", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn patch_address_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

// delete_endpoint_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn delete_endpoint_start[&h](heap: &!h Heap, id: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "delete_endpoint", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// delete_endpoint: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn delete_endpoint[&h, &c](heap: &!h Heap, conn: &!c Conn, id: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "delete_endpoint", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn delete_endpoint_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn delete_endpoint_setval[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 1);
    return pg.int_text(m, from, to);
}

pub fn delete_endpoint_setval_is_null[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 1);
    return from < 0;
}

// schedules_due_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn schedules_due_start[&h](heap: &!h Heap, now: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, now);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "schedules_due", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// schedules_due: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn schedules_due[&h, &c](heap: &!h Heap, conn: &!c Conn, now: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, now);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "schedules_due", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn schedules_due_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn schedules_due_expr[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn schedules_due_event_type[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 2);
}

pub fn schedules_due_body[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 3);
}

pub fn schedules_due_base[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 4);
    return pg.int_text(m, from, to);
}

pub fn schedules_due_next_fire[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 5);
    return pg.int_text(m, from, to);
}

// advance_schedule_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn advance_schedule_start[&h](heap: &!h Heap, id: int, was_base: int, was_next: int, fired: int, next: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param_int(heap, ps, was_base);
    ps = pg.param_int(heap, ps, was_next);
    ps = pg.param_int(heap, ps, fired);
    ps = pg.param_int(heap, ps, next);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "advance_schedule", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// advance_schedule: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn advance_schedule[&h, &c](heap: &!h Heap, conn: &!c Conn, id: int, was_base: int, was_next: int, fired: int, next: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param_int(heap, ps, was_base);
    ps = pg.param_int(heap, ps, was_next);
    ps = pg.param_int(heap, ps, fired);
    ps = pg.param_int(heap, ps, next);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "advance_schedule", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

// create_schedule_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn create_schedule_start[&h, &a1, &a2, &a3](heap: &!h Heap, expr: &a1 [byte], event_type: &a2 [byte], body: &a3 [byte], enabled: bool, now: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param(heap, ps, expr);
    ps = pg.param(heap, ps, event_type);
    ps = pg.param(heap, ps, body);
    ps = pg.param_bool(heap, ps, enabled);
    ps = pg.param_int(heap, ps, now);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "create_schedule", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// create_schedule: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn create_schedule[&h, &c, &a1, &a2, &a3](heap: &!h Heap, conn: &!c Conn, expr: &a1 [byte], event_type: &a2 [byte], body: &a3 [byte], enabled: bool, now: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param(heap, ps, expr);
    ps = pg.param(heap, ps, event_type);
    ps = pg.param(heap, ps, body);
    ps = pg.param_bool(heap, ps, enabled);
    ps = pg.param_int(heap, ps, now);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "create_schedule", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn create_schedule_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn create_schedule_expr[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn create_schedule_event_type[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 2);
}

pub fn create_schedule_body[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 3);
}

pub fn create_schedule_enabled[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 4);
    return pg.bool_text(m, from, to);
}

pub fn create_schedule_created_at[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 5);
    return pg.int_text(m, from, to);
}

pub fn create_schedule_last_fired[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 6);
    return pg.int_text(m, from, to);
}

pub fn create_schedule_next_fire[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 7);
    return pg.int_text(m, from, to);
}

// schedule_by_id_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn schedule_by_id_start[&h](heap: &!h Heap, id: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "schedule_by_id", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// schedule_by_id: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn schedule_by_id[&h, &c](heap: &!h Heap, conn: &!c Conn, id: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "schedule_by_id", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn schedule_by_id_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn schedule_by_id_expr[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn schedule_by_id_event_type[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 2);
}

pub fn schedule_by_id_body[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 3);
}

pub fn schedule_by_id_enabled[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 4);
    return pg.bool_text(m, from, to);
}

pub fn schedule_by_id_created_at[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 5);
    return pg.int_text(m, from, to);
}

pub fn schedule_by_id_last_fired[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 6);
    return pg.int_text(m, from, to);
}

pub fn schedule_by_id_next_fire[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 7);
    return pg.int_text(m, from, to);
}

// schedules_all_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn schedules_all_start[&h](heap: &!h Heap) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "schedules_all", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// schedules_all: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn schedules_all[&h, &c](heap: &!h Heap, conn: &!c Conn) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "schedules_all", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn schedules_all_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn schedules_all_expr[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn schedules_all_event_type[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 2);
}

pub fn schedules_all_body[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 3);
}

pub fn schedules_all_enabled[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 4);
    return pg.bool_text(m, from, to);
}

pub fn schedules_all_created_at[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 5);
    return pg.int_text(m, from, to);
}

pub fn schedules_all_last_fired[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 6);
    return pg.int_text(m, from, to);
}

pub fn schedules_all_next_fire[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 7);
    return pg.int_text(m, from, to);
}

// patch_schedule_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn patch_schedule_start[&h, &a2, &a3, &a4](heap: &!h Heap, id: int, expr: &a2 [byte], expr_given: bool, event_type: &a3 [byte], event_type_given: bool, body: &a4 [byte], body_given: bool, enabled: bool, enabled_given: bool, now: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    if expr_given {
        ps = pg.param(heap, ps, expr);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if event_type_given {
        ps = pg.param(heap, ps, event_type);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if body_given {
        ps = pg.param(heap, ps, body);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if enabled_given {
        ps = pg.param_bool(heap, ps, enabled);
    } else {
        ps = pg.param_null(heap, ps);
    }
    ps = pg.param_int(heap, ps, now);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "patch_schedule", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// patch_schedule: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn patch_schedule[&h, &c, &a2, &a3, &a4](heap: &!h Heap, conn: &!c Conn, id: int, expr: &a2 [byte], expr_given: bool, event_type: &a3 [byte], event_type_given: bool, body: &a4 [byte], body_given: bool, enabled: bool, enabled_given: bool, now: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    if expr_given {
        ps = pg.param(heap, ps, expr);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if event_type_given {
        ps = pg.param(heap, ps, event_type);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if body_given {
        ps = pg.param(heap, ps, body);
    } else {
        ps = pg.param_null(heap, ps);
    }
    if enabled_given {
        ps = pg.param_bool(heap, ps, enabled);
    } else {
        ps = pg.param_null(heap, ps);
    }
    ps = pg.param_int(heap, ps, now);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "patch_schedule", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn patch_schedule_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn patch_schedule_expr[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn patch_schedule_event_type[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 2);
}

pub fn patch_schedule_body[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 3);
}

pub fn patch_schedule_enabled[&m](m: &m [byte], row: int) -> [] bool {
    let (from, to) = pg.value(m, row, 4);
    return pg.bool_text(m, from, to);
}

pub fn patch_schedule_created_at[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 5);
    return pg.int_text(m, from, to);
}

pub fn patch_schedule_last_fired[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 6);
    return pg.int_text(m, from, to);
}

pub fn patch_schedule_next_fire[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 7);
    return pg.int_text(m, from, to);
}

// delete_schedule_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn delete_schedule_start[&h](heap: &!h Heap, id: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "delete_schedule", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// delete_schedule: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn delete_schedule[&h, &c](heap: &!h Heap, conn: &!c Conn, id: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "delete_schedule", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn delete_schedule_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

// Parse every query above on this connection, once, after login: PostgreSQL then parses and plans each
// one once instead of on every call. Answers the reply of the first refusal (`pg.failure` says what the
// server objected to) or an empty one, and a status; the queries are not to be run unless both are clean.
pub fn prepare_all[&h, &c](heap: &!h Heap, conn: &!c Conn) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var reply = buffer.empty(heap, 1);
    var status = 0;
    let (r0, s0) = pg.prepare_after(heap, conn, reply, status, "add_attempt", "insert into attempts (endpoint, event, replay, attempt, outcome, status, at_ms, latency_ms, reason) values ($1, $2, $3, $4, $5, $6, $7, $8, $9) on conflict do nothing");
    reply = r0;
    status = s0;
    let (r1, s1) = pg.prepare_after(heap, conn, reply, status, "prune_attempts", "delete from attempts where ctid in (select ctid from attempts where at_ms < $1::bigint limit $2::int)");
    reply = r1;
    status = s1;
    let (r2, s2) = pg.prepare_after(heap, conn, reply, status, "attempts_of", "select endpoint, replay, attempt, outcome, status, at_ms, latency_ms, reason from attempts where event = $1 order by endpoint, replay, attempt limit 200");
    reply = r2;
    status = s2;
    let (r3, s3) = pg.prepare_after(heap, conn, reply, status, "endpoints_all", "select id, host, port, secret, types, headers, secret_old, secret_old_until, concurrency, rate from endpoints order by id");
    reply = r3;
    status = s3;
    let (r4, s4) = pg.prepare_after(heap, conn, reply, status, "add_endpoint", "insert into endpoints (id, host, port, secret, types, headers, secret_old, secret_old_until, concurrency, rate) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) on conflict do nothing");
    reply = r4;
    status = s4;
    let (r5, s5) = pg.prepare_after(heap, conn, reply, status, "create_endpoint", "insert into endpoints (id, host, port, secret, types, headers, concurrency, rate) select greatest(nextval('endpoint_ids'), coalesce((select max(id) from endpoints), -1) + 1), $1::text, $2::int, $3::text, $4::text, $5::text, $6::int, $7::int returning id");
    reply = r5;
    status = s5;
    let (r6, s6) = pg.prepare_after(heap, conn, reply, status, "patch_endpoint", "update endpoints set host = $2::text, port = $3::int, secret_old = case when $4::text is not null then (case when coalesce($7::bigint, 0) > 0 then secret else '' end) when $7::bigint is not null then (case when $7::bigint > 0 then secret_old else '' end) else secret_old end, secret_old_until = case when $4::text is not null then (case when coalesce($7::bigint, 0) > 0 then (extract(epoch from clock_timestamp()) * 1000)::bigint + $7::bigint else 0 end) when $7::bigint is not null then (case when $7::bigint > 0 and secret_old <> '' then (extract(epoch from clock_timestamp()) * 1000)::bigint + $7::bigint else 0 end) else secret_old_until end, secret = coalesce($4::text, secret), types = coalesce($5::text, types), headers = coalesce($6::text, headers), concurrency = coalesce($8::int, concurrency), rate = coalesce($9::int, rate) where id = $1::int returning id");
    reply = r6;
    status = s6;
    let (r7, s7) = pg.prepare_after(heap, conn, reply, status, "patch_address", "update endpoints set host = $2::text, port = $3::int where id = $1::int returning id");
    reply = r7;
    status = s7;
    let (r8, s8) = pg.prepare_after(heap, conn, reply, status, "delete_endpoint", "with gone as (delete from endpoints where id = $1::int returning id) select id, setval('endpoint_ids', greatest(nextval('endpoint_ids'), id), true) from gone");
    reply = r8;
    status = s8;
    let (r9, s9) = pg.prepare_after(heap, conn, reply, status, "schedules_due", "select id, expr, event_type, body, base, next_fire from schedules where enabled and next_fire <= $1::bigint order by next_fire, id limit 32");
    reply = r9;
    status = s9;
    let (r10, s10) = pg.prepare_after(heap, conn, reply, status, "advance_schedule", "update schedules set last_fired = case when $4::bigint > 0 then $4::bigint else last_fired end, next_fire = $5::bigint where id = $1::bigint and base = $2::bigint and next_fire = $3::bigint");
    reply = r10;
    status = s10;
    let (r11, s11) = pg.prepare_after(heap, conn, reply, status, "create_schedule", "insert into schedules (expr, event_type, body, enabled, created_at, base) select $1::text, $2::text, $3::text, $4::boolean, $5::bigint, $5::bigint where (select count(*) from schedules) < 64 returning id, expr, event_type, body, enabled, created_at, last_fired, next_fire");
    reply = r11;
    status = s11;
    let (r12, s12) = pg.prepare_after(heap, conn, reply, status, "schedule_by_id", "select id, expr, event_type, body, enabled, created_at, last_fired, next_fire from schedules where id = $1::bigint");
    reply = r12;
    status = s12;
    let (r13, s13) = pg.prepare_after(heap, conn, reply, status, "schedules_all", "select id, expr, event_type, body, enabled, created_at, last_fired, next_fire from schedules order by id limit 64");
    reply = r13;
    status = s13;
    let (r14, s14) = pg.prepare_after(heap, conn, reply, status, "patch_schedule", "update schedules set expr = coalesce($2::text, expr), event_type = coalesce($3::text, event_type), body = coalesce($4::text, body), enabled = coalesce($5::boolean, enabled), base = case when $2::text is not null or ($5::boolean and not enabled) then greatest(base, $6::bigint) else base end, next_fire = case when $2::text is not null or ($5::boolean and not enabled) then 0 else next_fire end where id = $1::bigint returning id, expr, event_type, body, enabled, created_at, last_fired, next_fire");
    reply = r14;
    status = s14;
    let (r15, s15) = pg.prepare_after(heap, conn, reply, status, "delete_schedule", "delete from schedules where id = $1::bigint returning id");
    reply = r15;
    status = s15;
    return (reply, status);
}

// The same statements as the bytes to send after a login (Parse and Sync for each, in order) and how many there are,
// for a pool that logs in by itself: `pg.pool.reconnect` takes them, and prepares them again on every connection
// it makes.
pub fn prepare_script[&h](heap: &!h Heap) -> [heap] (buffer.Buffer, int) {
    var script = buffer.empty(heap, 256);
    script = pg.parse_append(heap, script, "add_attempt", "insert into attempts (endpoint, event, replay, attempt, outcome, status, at_ms, latency_ms, reason) values ($1, $2, $3, $4, $5, $6, $7, $8, $9) on conflict do nothing");
    script = pg.parse_append(heap, script, "prune_attempts", "delete from attempts where ctid in (select ctid from attempts where at_ms < $1::bigint limit $2::int)");
    script = pg.parse_append(heap, script, "attempts_of", "select endpoint, replay, attempt, outcome, status, at_ms, latency_ms, reason from attempts where event = $1 order by endpoint, replay, attempt limit 200");
    script = pg.parse_append(heap, script, "endpoints_all", "select id, host, port, secret, types, headers, secret_old, secret_old_until, concurrency, rate from endpoints order by id");
    script = pg.parse_append(heap, script, "add_endpoint", "insert into endpoints (id, host, port, secret, types, headers, secret_old, secret_old_until, concurrency, rate) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) on conflict do nothing");
    script = pg.parse_append(heap, script, "create_endpoint", "insert into endpoints (id, host, port, secret, types, headers, concurrency, rate) select greatest(nextval('endpoint_ids'), coalesce((select max(id) from endpoints), -1) + 1), $1::text, $2::int, $3::text, $4::text, $5::text, $6::int, $7::int returning id");
    script = pg.parse_append(heap, script, "patch_endpoint", "update endpoints set host = $2::text, port = $3::int, secret_old = case when $4::text is not null then (case when coalesce($7::bigint, 0) > 0 then secret else '' end) when $7::bigint is not null then (case when $7::bigint > 0 then secret_old else '' end) else secret_old end, secret_old_until = case when $4::text is not null then (case when coalesce($7::bigint, 0) > 0 then (extract(epoch from clock_timestamp()) * 1000)::bigint + $7::bigint else 0 end) when $7::bigint is not null then (case when $7::bigint > 0 and secret_old <> '' then (extract(epoch from clock_timestamp()) * 1000)::bigint + $7::bigint else 0 end) else secret_old_until end, secret = coalesce($4::text, secret), types = coalesce($5::text, types), headers = coalesce($6::text, headers), concurrency = coalesce($8::int, concurrency), rate = coalesce($9::int, rate) where id = $1::int returning id");
    script = pg.parse_append(heap, script, "patch_address", "update endpoints set host = $2::text, port = $3::int where id = $1::int returning id");
    script = pg.parse_append(heap, script, "delete_endpoint", "with gone as (delete from endpoints where id = $1::int returning id) select id, setval('endpoint_ids', greatest(nextval('endpoint_ids'), id), true) from gone");
    script = pg.parse_append(heap, script, "schedules_due", "select id, expr, event_type, body, base, next_fire from schedules where enabled and next_fire <= $1::bigint order by next_fire, id limit 32");
    script = pg.parse_append(heap, script, "advance_schedule", "update schedules set last_fired = case when $4::bigint > 0 then $4::bigint else last_fired end, next_fire = $5::bigint where id = $1::bigint and base = $2::bigint and next_fire = $3::bigint");
    script = pg.parse_append(heap, script, "create_schedule", "insert into schedules (expr, event_type, body, enabled, created_at, base) select $1::text, $2::text, $3::text, $4::boolean, $5::bigint, $5::bigint where (select count(*) from schedules) < 64 returning id, expr, event_type, body, enabled, created_at, last_fired, next_fire");
    script = pg.parse_append(heap, script, "schedule_by_id", "select id, expr, event_type, body, enabled, created_at, last_fired, next_fire from schedules where id = $1::bigint");
    script = pg.parse_append(heap, script, "schedules_all", "select id, expr, event_type, body, enabled, created_at, last_fired, next_fire from schedules order by id limit 64");
    script = pg.parse_append(heap, script, "patch_schedule", "update schedules set expr = coalesce($2::text, expr), event_type = coalesce($3::text, event_type), body = coalesce($4::text, body), enabled = coalesce($5::boolean, enabled), base = case when $2::text is not null or ($5::boolean and not enabled) then greatest(base, $6::bigint) else base end, next_fire = case when $2::text is not null or ($5::boolean and not enabled) then 0 else next_fire end where id = $1::bigint returning id, expr, event_type, body, enabled, created_at, last_fired, next_fire");
    script = pg.parse_append(heap, script, "delete_schedule", "delete from schedules where id = $1::bigint returning id");
    return (script, 16);
}
