// Generated by pgen from sql/queries.sql against hooks. Do not edit: change the SQL and run pgen again.
//
// Each query is a function that runs it (`<name>`: the whole reply and a status, 0 for ok), one that only
// encodes the request for `pg.pool.submit` (`<name>_start`), and one accessor per result column
// (`<name>_<column>`, read from a row as `pg.first_row`/`pg.next_row` give it; `_is_null` where the
// column can be NULL). Call `prepare_all` once after login, before the first query.
edition 5;

module queries;

import std.buffer;
import pg;

// add_attempt_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn add_attempt_start[&h](heap: &!h Heap, endpoint: int, event: int, replay: int, attempt: int, outcome: int, status: int, at_ms: int, latency_ms: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, endpoint);
    ps = pg.param_int(heap, ps, event);
    ps = pg.param_int(heap, ps, replay);
    ps = pg.param_int(heap, ps, attempt);
    ps = pg.param_int(heap, ps, outcome);
    ps = pg.param_int(heap, ps, status);
    ps = pg.param_int(heap, ps, at_ms);
    ps = pg.param_int(heap, ps, latency_ms);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "add_attempt", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// add_attempt: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn add_attempt[&h, &c](heap: &!h Heap, conn: &!c Conn, endpoint: int, event: int, replay: int, attempt: int, outcome: int, status: int, at_ms: int, latency_ms: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, endpoint);
    ps = pg.param_int(heap, ps, event);
    ps = pg.param_int(heap, ps, replay);
    ps = pg.param_int(heap, ps, attempt);
    ps = pg.param_int(heap, ps, outcome);
    ps = pg.param_int(heap, ps, status);
    ps = pg.param_int(heap, ps, at_ms);
    ps = pg.param_int(heap, ps, latency_ms);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "add_attempt", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

// Parse every query above on this connection, once, after login: PostgreSQL then parses and plans each
// one once instead of on every call. Answers the reply of the first refusal (`pg.failure` says what the
// server objected to) or an empty one, and a status; the queries are not to be run unless both are clean.
pub fn prepare_all[&h, &c](heap: &!h Heap, conn: &!c Conn) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var reply = buffer.empty(heap, 1);
    var status = 0;
    let (r0, s0) = pg.prepare_after(heap, conn, reply, status, "add_attempt", "insert into attempts (endpoint, event, replay, attempt, outcome, status, at_ms, latency_ms) values ($1, $2, $3, $4, $5, $6, $7, $8) on conflict do nothing");
    reply = r0;
    status = s0;
    return (reply, status);
}
