// Generated by pgen from sql/queries.sql against hooks. Do not edit: change the SQL and run pgen again.
//
// Each query is a function that runs it (`<name>`: the whole reply and a status, 0 for ok), one that only
// encodes the request for `pg.pool.submit` (`<name>_start`), and one accessor per result column
// (`<name>_<column>`, read from a row as `pg.first_row`/`pg.next_row` give it; `_is_null` where the
// column can be NULL). Call `prepare_all` once after login, before the first query.
edition 5;

module queries;

import std.buffer;
import pg;

// add_attempt_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn add_attempt_start[&h](heap: &!h Heap, endpoint: int, event: int, replay: int, attempt: int, outcome: int, status: int, at_ms: int, latency_ms: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, endpoint);
    ps = pg.param_int(heap, ps, event);
    ps = pg.param_int(heap, ps, replay);
    ps = pg.param_int(heap, ps, attempt);
    ps = pg.param_int(heap, ps, outcome);
    ps = pg.param_int(heap, ps, status);
    ps = pg.param_int(heap, ps, at_ms);
    ps = pg.param_int(heap, ps, latency_ms);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "add_attempt", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// add_attempt: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn add_attempt[&h, &c](heap: &!h Heap, conn: &!c Conn, endpoint: int, event: int, replay: int, attempt: int, outcome: int, status: int, at_ms: int, latency_ms: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, endpoint);
    ps = pg.param_int(heap, ps, event);
    ps = pg.param_int(heap, ps, replay);
    ps = pg.param_int(heap, ps, attempt);
    ps = pg.param_int(heap, ps, outcome);
    ps = pg.param_int(heap, ps, status);
    ps = pg.param_int(heap, ps, at_ms);
    ps = pg.param_int(heap, ps, latency_ms);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "add_attempt", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

// attempts_of_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn attempts_of_start[&h](heap: &!h Heap, event: int) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, event);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "attempts_of", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// attempts_of: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn attempts_of[&h, &c](heap: &!h Heap, conn: &!c Conn, event: int) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, event);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "attempts_of", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn attempts_of_endpoint[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_replay[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 1);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_attempt[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 2);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_outcome[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 3);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_status[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 4);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_at_ms[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 5);
    return pg.int_text(m, from, to);
}

pub fn attempts_of_latency_ms[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 6);
    return pg.int_text(m, from, to);
}

// endpoints_all_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn endpoints_all_start[&h](heap: &!h Heap) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "endpoints_all", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// endpoints_all: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn endpoints_all[&h, &c](heap: &!h Heap, conn: &!c Conn) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "endpoints_all", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn endpoints_all_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

pub fn endpoints_all_host[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 1);
}

pub fn endpoints_all_port[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 2);
    return pg.int_text(m, from, to);
}

pub fn endpoints_all_secret[&m](m: &m [byte], row: int) -> [] (int, int) {
    return pg.value(m, row, 3);
}

// add_endpoint_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn add_endpoint_start[&h, &a2, &a4](heap: &!h Heap, id: int, host: &a2 [byte], port: int, secret: &a4 [byte]) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "add_endpoint", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// add_endpoint: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn add_endpoint[&h, &c, &a2, &a4](heap: &!h Heap, conn: &!c Conn, id: int, host: &a2 [byte], port: int, secret: &a4 [byte]) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param_int(heap, ps, id);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "add_endpoint", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

// create_endpoint_start: the request, encoded, for `pg.pool.submit`; the reply is read with the accessors below
pub fn create_endpoint_start[&h, &a1, &a3](heap: &!h Heap, host: &a1 [byte], port: int, secret: &a3 [byte]) -> [heap] buffer.Buffer {
    var ps = pg.params(heap);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    var request = buffer.empty(heap, 1);
    borrow ps as &pr in {
        buffer.drop(heap, request);
        request = pg.bind_named(heap, "create_endpoint", pr);
    }
    pg.drop_params(heap, ps);
    return request;
}

// create_endpoint: the whole reply, and a status (0 ok); `pg.failure(reply)` is the server's error, if any
pub fn create_endpoint[&h, &c, &a1, &a3](heap: &!h Heap, conn: &!c Conn, host: &a1 [byte], port: int, secret: &a3 [byte]) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var ps = pg.params(heap);
    ps = pg.param(heap, ps, host);
    ps = pg.param_int(heap, ps, port);
    ps = pg.param(heap, ps, secret);
    var reply = buffer.empty(heap, 1);
    var status = 0;
    borrow ps as &pr in {
        let (r, s) = pg.run_named(heap, conn, "create_endpoint", pr);
        buffer.drop(heap, reply);
        reply = r;
        status = s;
    }
    pg.drop_params(heap, ps);
    return (reply, status);
}

pub fn create_endpoint_id[&m](m: &m [byte], row: int) -> [] int {
    let (from, to) = pg.value(m, row, 0);
    return pg.int_text(m, from, to);
}

// Parse every query above on this connection, once, after login: PostgreSQL then parses and plans each
// one once instead of on every call. Answers the reply of the first refusal (`pg.failure` says what the
// server objected to) or an empty one, and a status; the queries are not to be run unless both are clean.
pub fn prepare_all[&h, &c](heap: &!h Heap, conn: &!c Conn) -> [heap, conn_read, conn_write] (buffer.Buffer, int) {
    var reply = buffer.empty(heap, 1);
    var status = 0;
    let (r0, s0) = pg.prepare_after(heap, conn, reply, status, "add_attempt", "insert into attempts (endpoint, event, replay, attempt, outcome, status, at_ms, latency_ms) values ($1, $2, $3, $4, $5, $6, $7, $8) on conflict do nothing");
    reply = r0;
    status = s0;
    let (r1, s1) = pg.prepare_after(heap, conn, reply, status, "attempts_of", "select endpoint, replay, attempt, outcome, status, at_ms, latency_ms from attempts where event = $1 order by endpoint, replay, attempt limit 200");
    reply = r1;
    status = s1;
    let (r2, s2) = pg.prepare_after(heap, conn, reply, status, "endpoints_all", "select id, host, port, secret from endpoints order by id");
    reply = r2;
    status = s2;
    let (r3, s3) = pg.prepare_after(heap, conn, reply, status, "add_endpoint", "insert into endpoints (id, host, port, secret) values ($1, $2, $3, $4) on conflict do nothing");
    reply = r3;
    status = s3;
    let (r4, s4) = pg.prepare_after(heap, conn, reply, status, "create_endpoint", "insert into endpoints (id, host, port, secret) select greatest(nextval('endpoint_ids'), coalesce((select max(id) from endpoints), -1) + 1), $1::text, $2::int, $3::text returning id");
    reply = r4;
    status = s4;
    return (reply, status);
}
